### ISSUE TITLE
Top-k results undertermined

### ISSUE THREAD

**Issue by janasim** [propi/rdfrules#51]
When running a task with too many rules that corresponds to the top-k metric the results differs, example:
[topk_issue.zip](https://github.com/propi/rdfrules/files/5297729/topk_issue.zip)
It becomes a problem when trying to instantiate a rule from the output.

**Comment by propi** [comment]
The top-k approach is not deterministic due to parallelism. The problem is if there are lots of rules with the same lowest support in the top-k queue. The ordering of these rules is not stable. The solution is creating a new mode of top-k approach where the tail of the last rules with a same support of the queue will be returned. In this mode the result may contain more than k rules, but it will be deterministic.

I add this to future work.

**Comment by propi** [comment]
If you want to hold mined top-k rules for other use, I recommend to save rules into the memory or disk cache immediately after mining.

**Comment by propi** [comment]
"Allow overflow" option added in the top-k consumer.
