### ISSUE TITLE
add possibility to output contingency table for each rule

### ISSUE THREAD

**Issue by kliegr** [propi/rdfrules#54]
Standard association rules are complemented by the four field contingency table, which allows to compute - among other measures -- also statistical tests like chi-square. Would it be possible to output a similar table?

**Comment by propi** [comment]
Assume CWA and rule: (?a \<wasBornIn\> ?b) => (?a \<diedIn\> ?b)
Then the contingency table should have the following form:
|   |  (?a \<diedIn\> ?b) | !(?a \<diedIn\> ?b)  |
|---|---|---|
| (?a \<wasBornIn\> ?b)  |  a | b  |
| !(?a \<wasBornIn\> ?b)  | c  | d  |

- a = support
- b = all predicted missing triples
- c = all triples covered by the head minus support
- d = what about this value? All triples in the KG which does not satisfy a, b, c? Is it valid? I don't think so, because most of other triples may have different context (it is not as a table which relates to just one context).

**Comment by propi** [comment]
You can use the "predict" operation on a rule and then to execute the "evaluate" action to get this tab. But it is still hard or impossible (for OWA) to determine "true negatives".
